language: python
python:
  - "3.6"
sudo: required
node_js:
  - '8'
branches:
  only:
    - master
cache:
  yarn: true
addons:
  ssh_known_hosts: splitgraph.com
script:
  # Build docs from Splitgraph's master branch
  - git clone https://github.com/splitgraph/splitgraph.git && cd splitgraph
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install -E ingestion
  - cd docs && poetry run make clean html
  # Build commandline docs
  - cd .. && poetry run python ../website/generate_markdown_commandline_reference.py docs/sgr -f
  # Build static site
  - cd ../website && yarn install && yarn build
  # Inject API docs into the site
  - cp ../splitgraph/docs/_build/html -r build/splitgraph/sphinx
after_success:
  # deploy build/splitgraph
  # decrypt our key
  - openssl aes-256-cbc -K $encrypted_57ed443d832d_key -iv $encrypted_57ed443d832d_iv -in ../travis_rsa.enc -out travis_rsa -d
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa
  # get us to trust splitgraph.com
  - echo "[splitgraph.com]:9092 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEApm3oOAWtA+EUcWykQwAoX+B+5q+hAK1jHPOAsmdttEZxBe/yjzfn31ot2cp+SS8TRy4PZxMeFlfqx/OdIeLuwbPm6iOi+6LlgTTkaxLbvgv6ugLEXLfMgQ5KBOPZ3w7SGw6K4yO7s15zNri5NLx0juZELoA4jyVrq/A25l9GDW6WiBe8LLrdn/Lf6jOBhJKI8M8krgCdrnRiVKNmAgSo7iibFBoefum6wm8hwzoKTaot8SFB1iVhblgdcLrDwziE8zuwtjSjy9Bf+IVsLag6+ShByXbh5tWrRDpN3IYDyjzUgJtIkKTGP2uSuBrdRXMgyy7NyavKtAwSNLgXJlxfPQ==" >> $HOME/.ssh/known_hosts
  - bash ../remote_deploy.sh
