language: python
python:
  - "3.6"
sudo: required
node_js:
  - '8'
#branches:
#  only:
#    - master
cache:
  yarn: true
script:
  # Build docs from Splitgraph's master branch
  - git clone https://github.com/splitgraph/splitgraph.git && cd splitgraph
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install
  - cd docs && poetry run make clean html
  # Build commandline docs
  - cd .. && poetry run python ../website/generate_markdown_commandline_reference.py docs/sgr -f
  # Build static site
  - cd ../website && yarn install && yarn build
  # Inject API docs into the site
  - cp ../splitgraph/docs/_build/html -r build/splitgraph/sphinx
  # TODO: push build/splitgraph out to target
