name: Build and deploy preview

on: [push, pull_request]

jobs:
  build_and_deploy_preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: ./setup.sh
      - uses: actions/cache@v1
        with:
          path: /home/runner/yarn-cache
          key: yarncache
      - run: ./.ci/install.sh
        env:
          YARN_CACHE_FOLDER: /home/runner/yarn-cache
      - run: ./.ci/build.sh
      - run: ./.ci/deploy_preview.sh
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
          NOW_PROJECT_ID: ${{ secrets.NOW_PROJECT_ID }}
          NOW_ORG_ID: ${{ secrets.NOW_ORG_ID }}
      - uses: actions/upload-artifact@v2
        with:
          name: website
          path: ./docs/out
