name: Build and deploy preview

on: [push, pull_request]

jobs:
  build_and_deploy_preview:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: ./setup.sh
      - uses: actions/cache@v1
        with:
          path: /home/runner/yarn-cache
          key: yarncache
      - run: ./.ci/install.sh
        env:
          YARN_CACHE_FOLDER: /home/runner/yarn-cache
      - run: ./.ci/build.sh
      - run: ./.ci/deploy_preview.sh
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
          NOW_PROJECT_ID: ${{ secrets.NOW_PROJECT_ID }}
          NOW_ORG_ID: ${{ secrets.NOW_ORG_ID }}
      - uses: actions/upload-artifact@v2
        with:
          name: website
          path: ./docs/out
      - run: ./.ci/get_preview_url.sh preview_url.txt
      - uses: actions/upload-artifact@v2
        with:
          name: preview_url
          path: ./preview_url.txt

  release_master:
    runs-on: ubuntu-latest
    needs: build_and_deploy_preview
    if: github.ref == 'refs/heads/next'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: website
          path: website
      - name: List artifact
        run: ls -R website
      - name: Remove preview artifacts (robots.txt)
        run: rm website/robots.txt
